name: Build a Docker image
description: |
  This action does the actual building of an image, based on the given
  parameters.

inputs:
  dockerfile:
    description: Dockerfile that describes the image
    required: true
  docker-args:
    description: Arguments to pass to the docker build-process
  labels:
    description: Labels to add to the image
  output:
    description: Controls what should be done with the image(s) after building
  platforms:
    description: The platforms for which to build the image
    required: true
  tags:
    description: All tags for the image
  target:
    description: Which stage in the Dockerfile to build
    required: true

runs:
  using: composite
  steps:
    - name: Build Docker image
      uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8 # v6.19.2
      with:
        build-args: |
          ${{ inputs.docker-args }}
        context: .
        file: ${{ inputs.dockerfile }}
        labels: ${{ inputs.labels }}
        outputs: ${{ inputs.output }}
        platforms: ${{ inputs.platforms }}
        tags: ${{ inputs.tags }}
        target: ${{ inputs.target }}
