name: Node CI

on:
  pull_request:
    paths:
      - '.github/workflows/nodejs.yml'
      - '.nvmrc'
      - '.pnpmfile.cjs'
      - '.versions/node_*'
      - 'bin/**'
      - 'data/**'
      - 'index.cjs'
      - 'lib/**'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - 'devenv*'
  push:
    branches:
      - master
      - release/*
    tags:
      - 'v*'
    paths:
      - '.github/workflows/nodejs.yml'
      - '.nvmrc'
      - '.pnpmfile.cjs'
      - '.versions/node_*'
      - 'bin/**'
      - 'data/**'
      - 'index.cjs'
      - 'lib/**'
      - 'package.json'
      - 'pnpm-lock.yaml'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  NEXUS_URL: ${{ secrets.NEXUS_URL }}

# https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/controlling-permissions-for-github_token
permissions: {}

jobs:
  read-node-versions:
    runs-on: 'ubuntu-latest'
    outputs:
      node-versions: ${{ steps.read-versions.outputs.versions }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - id: read-versions
        run: |
          VERSIONS=[`awk 'BEGIN {ORS=""}; NR>2 && NR%2==0 {print ","}; FNR==2 {print "'\''"$1"'\''"}' .versions/node_*`]
          echo "versions=$VERSIONS" >> "$GITHUB_OUTPUT"

  matrix-unit-test:
    needs: read-node-versions
    strategy:
      fail-fast: false
      matrix:
        node-version: ${{ fromJSON(needs.read-node-versions.outputs.node-versions) }}
        os: ['ubuntu-22.04', 'ubuntu-24.04', 'windows-latest', 'windows-11-arm', 'ubuntu-22.04-arm', 'ubuntu-24.04-arm', 'macos-15', 'macos-latest']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Setup pnpm
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5.0.0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e  # v6.4.0
        with:
          node-version: ${{ matrix.node-version }}
          package-manager-cache: false
      - name: pnpm install, build and test
        shell: bash
        run: |
          pnpm install:frozen
          FETCH_LICENSE=true node bin/cdxgen.js --exclude test/\*\* -t js --deep
          pnpm test
        env:
          CI: true
          NPM_CONFIG_PROVENANCE: true
        
  depscan:
    continue-on-error: true
    runs-on: ["self-hosted", "ubuntu", "arm64"]
    permissions:
      contents: write  # needed for creating GH releases and uploading release assets
    strategy:
      fail-fast: false
      matrix:
        java-version: ['24']
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: 3.13
      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java-version }}
      - name: Trim CI agent
        run: rm -rf /tmp/docker-images-* /tmp/atom-* /tmp/mvn-deps*
      - name: Setup pnpm
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5.0.0
      - name: Setup Nexus usage
        run: echo "registry=$NEXUS_URL" > .npmrc
      - name: pnpm install
        run: |
          pnpm install:frozen
          python3 -m pip install --pre owasp-depscan[all] atom-tools
      - name: check sbom for vulns
        if: github.ref == 'refs/heads/master'
        run: |
          node bin/cdxgen.js -t js -t php -t jar -t ruby -t github -o $(pwd)/reports/sbom-build.cdx.json --include-formulation --export-proto --proto-bin-file $(pwd)/reports/sbom-build.cdx.proto --exclude "**/test/**" $(pwd)
          docker pull ghcr.io/cyclonedx/cdxgen:master
          node bin/cdxgen.js -t docker -o $(pwd)/reports/sbom-container-js.cdx.json ghcr.io/cyclonedx/cdxgen:master
          depscan --src $(pwd) --bom-dir $(pwd)/reports --reports-dir $(pwd)/reports --reachability-analyzer SemanticReachability --explain
        env:
          COLUMNS: 140
          JAVA_TOOL_OPTIONS: "-XX:UseSVE=0 -Dfile.encoding=UTF-8"
          FETCH_LICENSE: true
      - name: Generate atom and slices
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          node bin/cdxgen.js -t js -t php -t jar -t ruby -t github -o $(pwd)/reports/sbom-build.cdx.json --include-formulation --export-proto --proto-bin-file $(pwd)/reports/sbom-build.cdx.proto --exclude "**/test/**" $(pwd)
        env:
          FETCH_LICENSE: true
      - name: Upload atom and slices
        uses: softprops/action-gh-release@b4309332981a82ec1c5618f44dd2e27cc8bfbfda  # v3.0.0
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            reports/sbom-build.cdx.json
            reports/sbom-build.cdx.proto
      - name: Cleanup
        run: rm -rf /tmp/docker-images* /tmp/atom-* /tmp/mvn-deps*

  deno-build:
    strategy:
      fail-fast: true
      matrix:
        os: [windows, macos, ubuntu]
        include:
          - os: windows
            build: |
              deno compile --allow-read --allow-env --allow-run --allow-sys=uid,systemMemoryInfo,gid,osRelease,homedir --allow-write --allow-net --include=./data --include=./package.json --output cdxgenx.exe bin/cdxgen.js
              .\cdxgenx.exe --help
              (Get-FileHash .\cdxgenx.exe).hash | Out-File -FilePath .\cdxgenx.exe.sha256
#              deno compile --allow-read --allow-env --allow-run --allow-sys=uid,systemMemoryInfo,gid,osRelease,homedir --allow-write --allow-net --node-modules-dir=auto --allow-ffi --include=./data --include=./package.json --output evinse.exe bin/evinse.js
#              .\evinse.exe --help
#              (Get-FileHash .\evinse.exe).hash | Out-File -FilePath .\evinse.exe.sha256
            artifact: cdxgenx.exe
          - os: macos
            build: |
              deno compile --allow-read --allow-env --allow-run --allow-sys=uid,systemMemoryInfo,gid,homedir --allow-write --allow-net --include=./data --include=./package.json --target aarch64-apple-darwin --output cdxgenx-darwin-arm64 bin/cdxgen.js
              shasum -a 256 cdxgenx-darwin-arm64 > cdxgenx-darwin-arm64.sha256
              ./cdxgenx-darwin-arm64 --help
#              deno compile --allow-read --allow-env --allow-run --allow-sys=uid,systemMemoryInfo,gid,homedir --allow-write --allow-net --node-modules-dir=auto --allow-ffi --include=./data --include=./package.json --target aarch64-apple-darwin --output evinse-darwin-arm64 bin/evinse.js
#              shasum -a 256 evinse-darwin-arm64 > evinse-darwin-arm64.sha256
#              ./evinse-darwin-arm64 --help
            artifact: cdxgenx-darwin-arm64
          - os: ubuntu
            build: |
              deno compile --allow-read --allow-env --allow-run --allow-sys=uid,systemMemoryInfo,gid,homedir --allow-write --allow-net --include=./data --include=./package.json --output cdxgenx bin/cdxgen.js
              shasum -a 256 cdxgenx > cdxgenx.sha256
              chmod + cdxgenx
              ./cdxgenx --help
#              deno compile --allow-read --allow-env --allow-run --allow-sys=uid,systemMemoryInfo,gid,homedir --allow-write --allow-net --node-modules-dir=auto --allow-ffi --include=./data --include=./package.json --output evinse bin/evinse.js
#              shasum -a 256 evinse > evinse.sha256
#              chmod + evinse
#              ./evinse --help
            artifact: cdxgenx
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Setup pnpm
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5.0.0
      - name: Use Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e  # v6.4.0
        with:
          node-version-file: .nvmrc
          package-manager-cache: false
      - uses: denoland/setup-deno@667a34cdef165d8d2b2e98dde39547c9daac7282 # v2.0.4
        with:
          deno-version: 2.7.5
      - name: pnpm install, build and test
        run: |
          pnpm install:frozen
      - name: deno compile
        run: |
          deno info bin/cdxgen.js
          deno info bin/evinse.js
          mkdir build
          ${{ matrix.build }}
        continue-on-error: true
